title: Taras Kucherenko
#author: Taras Kucherenko
email: tarask@kth.se
description: > # this means to ignore newlines until "show_exerpts:"
  Ph.D. student: applying machine learning for social robotics. Building models for generating non-verbal behavior for virtual agents and humanoid robots.
# Working under supervision of Hedvig Kjlestrom in the EACare project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svito-zar.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  svito-zar
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: SvitozarTaras
    github:  svito-zar
    # facebook: jekyll
    linkedin: taras-kucherenko-9b049198
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - _pages/portfolio.md
 - _pages/publications.md
 - _pages/teaching.md
 - _pages/speaking.md
 - _pages/contact.md
 - _pages/defence.md
 #- _pages/datasets.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include: ['_pages']
exclude: [vendor]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
